### ISSUE TITLE
Beta Scanner - Issues (Scanner Hang)

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#133]
Not really sure how to log this, but here is what I experienced:

Using latest Beta HAMA as well.

- **Slow scanning/hang**.  Scanner would hang immediately after starting.  It looks like in the Plex scan logs, it hands when it finds a "doesn't exist, can't skip" despite that it is there and does exist.  A Plex dance on the show that it says might resolve the issue, it might not.  If I switch to the master branch, this issue does not exist.  Switching the scanner seems to make this issue come up.

For example. it will hit:

```
Feb 19, 2018 09:01:39.472 [9504] DEBUG - Adding subdirectory for scanner: "E:\Series\Green Green"
Feb 19, 2018 09:01:39.472 [9504] DEBUG - Adding subdirectory for scanner: "E:\Series\Grimgar of Fantasy and Ash"
Feb 19, 2018 09:01:39.472 [9504] DEBUG - Adding subdirectory for scanner: "E:\Series\Guilty Crown"
Feb 19, 2018 09:01:39.472 [9504] DEBUG - Adding subdirectory for scanner: "E:\Series\Gun Frontier"
Feb 19, 2018 09:01:39.472 [9504] DEBUG - Adding subdirectory for scanner: "E:\Series\Gundam Build Fighters"
Feb 19, 2018 09:01:39.472 [9504] DEBUG - Adding subdirectory for scanner: "E:\Series\Gundam Reconguista in G"
Feb 19, 2018 09:01:39.472 [9504] DEBUG - Adding subdirectory for scanner: "E:\Series\Gundam-san"
Feb 19, 2018 09:01:39.472 [9504] DEBUG - Adding subdirectory for scanner: "E:\Series\Gungrave"
Feb 19, 2018 09:01:39.472 [9504] DEBUG - Adding subdirectory for scanner: "E:\Series\Gunparade March"
Feb 19, 2018 09:01:39.472 [9504] DEBUG - Adding subdirectory for scanner: "E:\Series\Gurren Lagan"
Feb 19, 2018 09:01:39.473 [9504] DEBUG - Adding file for scanner: "E:\Series\X-Plex-Token.id"
Feb 19, 2018 09:01:39.476 [9504] DEBUG - File 'E:\Series\Gangsta\Gangsta. - 01 - Naughty Boys.mkv' didn't exist, can't skip.
Feb 19, 2018 09:03:29.677 [9504] DEBUG -       * Scanning 07-Ghost Season 1 Episode 1
Feb 19, 2018 09:03:29.677 [9504] DEBUG - Looking for path match for [E:\Series\07-Ghost\07-Ghost - 1 - The Future of Painful Thoughts is.mkv]
Feb 19, 2018 09:03:29.679 [9504] DEBUG - Path matched, we're reusing media item 164350
Feb 19, 2018 09:03:29.688 [9504] DEBUG -       * Scanning 07-Ghost Season 1 Episode 10
```

You can see all activity stops for about two minutes. If I Plex dance Gangtsa, then another show takes it's place.  All of the files it suggests do not exist, are present. 

Update Note:  while it is hung, it does appear during that time the individual logs are generating, but it still looks like nothing is happening. The scan wheel on Plex is just spinning. It seems like Plex will scan a bit, then generate logs, then start again.  A total scan takes around 10 minutes at times.

[logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1736978/logs.zip)

**Comment by mweber03** [comment]
Do you have the latest Scanner? Mine was super slow last week before I did that.

**Comment by sven-7** [comment]
Yeah - I grabbed the latest beta as of this posting to try it out.  It's still acting this way now.

**Comment by ZeroQI** [comment]
Cannot see in logs, if master branch scanner works will do a new scanner using more proper function calls

**Comment by sven-7** [comment]
Are there any logs I can provide to give you better clarity?

**Comment by ZeroQI** [comment]
The very method used is problematic.
The issue is if there is an error, it removes all files from the library and it needs to be recreated even if the scanner error is fixed. Also the error is not always indicated making it a royal pain in the ass to develop...

Nearly finished though, i will keep you posted
Current progress is there: https://gist.github.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d

**Comment by sven-7** [comment]
Great, thanks!  I can test whenever it's ready.

**Comment by ZeroQI** [comment]
https://gist.github.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d
Updated and is working for normal series and plexignore support (and useless zip support)
Grouping folders do not work and random folders in season folders should be working but not without season folders. working on that currently

**Comment by sven-7** [comment]
It's still hanging for me. It continues to get stuck on a missing file that actually isn't missing. 

This is from Logs\Plex Media Scanner.log

```
Feb 27, 2018 13:03:36.264 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Granblue Fantasy The Animation"
Feb 27, 2018 13:03:36.264 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Gravitation TV"
Feb 27, 2018 13:03:36.264 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Great Teacher Onizuka"
Feb 27, 2018 13:03:36.264 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Green Green"
Feb 27, 2018 13:03:36.264 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Grimgar of Fantasy and Ash"
Feb 27, 2018 13:03:36.264 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Guilty Crown"
Feb 27, 2018 13:03:36.264 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Gun Frontier"
Feb 27, 2018 13:03:36.264 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Gundam Build Fighters"
Feb 27, 2018 13:03:36.265 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Gundam Reconguista in G"
Feb 27, 2018 13:03:36.265 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Gundam-san"
Feb 27, 2018 13:03:36.265 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Gungrave"
Feb 27, 2018 13:03:36.265 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Gunparade March"
Feb 27, 2018 13:03:36.265 [12956] DEBUG - Adding subdirectory for scanner: "E:\Series\Gurren Lagann"
Feb 27, 2018 13:03:36.269 [12956] DEBUG - File 'F:\Series\Haikyuu!!\Haikyuu!! - 1 - The End & the Beginning.mkv' didn't exist, can't skip.

```

**Comment by ZeroQI** [comment]
Could be corrupted Plex database believe the ep is missing un plex database

**Comment by sven-7** [comment]
I checked for corruptions, per the Plex instructions, but everything came back okay. 

Also, now every show with a .id file is being added as an S0E501

<img width="705" alt="screen shot 2018-02-27 at 3 02 09 pm" src="https://user-images.githubusercontent.com/18091557/36751842-5d9e36b2-1bcf-11e8-9744-7485266c9307.png">

**Comment by ZeroQI** [comment]
if only leaving one root folder on f:, does it work or still complain

**Comment by sven-7** [comment]
As in only `F:/Series/` ? 

I have four drives with a Series folder on them and then all series sub-folders listed inside.

**Comment by ZeroQI** [comment]
yes, as it could be a bug in my code when it attack the 2nd folder or there is something in the filenames on f giving issues

**Comment by sven-7** [comment]
Ah. So right now my library is set to scan four harddrives.  Each drive has one main folder called `Series`. That is the only folder on each drive.

See below:

<img width="552" alt="screen shot 2018-02-27 at 6 18 37 pm" src="https://user-images.githubusercontent.com/18091557/36760936-c7d6a49a-1bea-11e8-8f3e-01638cdbca9a.png">

**Comment by sven-7** [comment]
It definitely does look like it gets caught on one drive before moving onto the next.

**Comment by ZeroQI** [comment]
so only f gives an error? would need the filelist then...

**Comment by sven-7** [comment]
No, they all give errors.

**Comment by ZeroQI** [comment]
Please test https://gist.github.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d
grouping folder support while keeping caching if ep folders present in season folder
Plexignore seem to work
Should be better system wise

**Comment by sven-7** [comment]
I am still having all .id files added as S0E501's.

**Comment by sven-7** [comment]
I made a two series library across two different root drives.  It supplies the scan error during it, but only after a second harddrive was added.  

After the Rain's .id file also shows up as a special. 

[Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1768429/Logs.zip)

**Comment by sven-7** [comment]
Here's a theory -- watching it live, it seems to scan one drive then create and write all the individual  `.filelist` and `.scanner` log files. Then it does that three more times over the course of all my drives. That might explain the pause between drives. 

The .id file showing up as a special only exists on the current version of the beta scanner.  It does not exist on the prior d23868d commit.

**Comment by ZeroQI** [comment]
just published on beta branch one without .plexignore and id file issue
grouping folders write twice the filelist. trying to solve that

**Comment by ZeroQI** [comment]
Published a new version, logging all scan calls in both filelist and scanner logs, much simpler to follow now and if it crashed we would have no filelist if only gathering for grouped folders.
Should not detect any non video ext as file now, small issue with splitext ignoring leading dots
Please let me know any issues

**Comment by sven-7** [comment]
Not seeing any lingering issues on my end.  

The scanner still seems to do things one HDD at a time.  The process seems to be:

1.  Scan E:/Series
2.  Make .scanner and .filelist for all in E:/Series
3.  Slight Pause
4.  Scan F:/Series
etc...

No .id files on the latest scanner. So good to go there.

**Comment by ZeroQI** [comment]
worked all day, added .plexignore full support. Please let me know any issues

**Comment by ZeroQI** [comment]
This should be stable
Worked all day due to fullpath on scan call path instead of relative path...

https://github.com/ZeroQI/Absolute-Series-Scanner/blob/Beta/Scanners/Series/Absolute%20Series%20Scanner.py

Please test and feedback and see if faster if possible.
Need to clear cleverly logs now

**Comment by sven-7** [comment]
It definitely seems a lot faster.  It look a few times to get through things.  Here is what happened:

1.  On the first scan, it removed about 300 series that I had.  The overall scan was several times faster in creating the logs. If I were to guess, it removed everything after my first drive (out of four).
2.  On the second scan, it added back about 150 of them.  Some of them only partially. 
3.  On the third scan, it got back up to the original number of series, with the exception of one episode I added during the first scan.
4.  On the fourth scan, it picked up the episode and everything looks to be back to normal. 
5.  Fifth scan was fairly quick. I think it's gone from about 10-12 minutes down to 3ish minutes.  I have 490 series right now, for perspective on how much is being scanned.

**Comment by ZeroQI** [comment]
@sven-7 Thanks for letting me know. Glad it is faster. 
Since it is scanned manually from the root folder i believe it had to un-do then re-do which it didn't like. Would be nice to create a separate library to scan from the start with that version. 

Looking now to make it faster with simple optimisations like cancelling the Plex naturally called scan instances, possibly not helping there, so we do things once and only if needed...

**Comment by sven-7** [comment]
No problem!

One more note on the Plex Dance.  I removed an entire drive's worth of series.  The scan deleted them all out, as expected.  Then it ran once I re-added them and went through the scan and agent process.  When I did the next drive, it removed all the series from drive 1, which it just completed.  After the drive 2 Plex dance process was completed and I hit re-scan, the Drive 1 series were added again.  The same thing happened with Drive 2 when I went to do the third. Not sure why it is deleting and re-adding twice.

**Comment by ZeroQI** [comment]
That would explain similar issue i have been having on a single root folder library
By plex dance do we mean the same?
- delete library
- Clean bundle
- empty trash
- optimise database
- recreate the library adding all root folders at once
I get the feeling the behaviour of Plex in regards to the scanner changed... Never wittnessed similar...

**Comment by sven-7** [comment]
I am not deleting the library (I didn't want to affect my watch counts).  I'm following the standard [Plex Dance per the forums.](https://forums.plex.tv/discussion/277433/the-plex-dance)

It does seem like Plex has changed something with the scanner.  It's odd that it needs to add-delete-then add again.  Other than that, your scanner is working great.

**Comment by ZeroQI** [comment]
@sven-7 makes sense now. You can however create a second library that point
to the same folders for tests i believe.
So from what i understand it is better apart for issues while migrating an
already existing library?

**Comment by sven-7** [comment]
Yes - I will likely create a smaller subset library to test on.

Correct - migrating an existing library may result in what seems like a double-scan.  Thus far, it does it once, and then it's good to go.

**Comment by sven-7** [comment]
Getting a weird error and super slow scanner all of a sudden...

From _root_scanner.log:

```
Library: 'Anime Series', root: 'E:\Series', path: '', files: '0', dirs: '181', Plex scan date: 2018-03-03 14:32:04
=============================================================================================================================================================
[no files detected]
-------------------------------------------------------------------------------------------------------------------------------------------------------------
07-Ghost                                                    , subdir_files:  25, reverse_path: ['07-Ghost']                            
91 Days                                                     , subdir_files:  13, reverse_path: ['91 Days']                             
A Certain Magical Index                                     , subdir_files:  48, reverse_path: ['A Certain Magical Index']             
A Certain Scientific Railgun                                , subdir_files:  48, reverse_path: ['A Certain Scientific Railgun']        
A Dark Rabbit Has Seven Lives                               , subdir_files:  12, reverse_path: ['A Dark Rabbit Has Seven Lives']       
A place further than the Universe                           , subdir_files:   9, reverse_path: ['A place further than the Universe']   
Abenobashi Mahou Shoutengai                                 , subdir_files:  13, reverse_path: ['Abenobashi Mahou Shoutengai']         
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
ACCA 13 -Territory Inspection Department                    , subdir_files:  12, reverse_path: ['ACCA 13 -Territory Inspection Department']
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Accel World                                                 , subdir_files:  24, reverse_path: ['Accel World']                         
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Ace of Diamond                                              , subdir_files: 126, reverse_path: ['Ace of Diamond']                      
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Active Raid                                                 , subdir_files:  24, reverse_path: ['Active Raid']                         
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Afro Samurai                                                , subdir_files:   5, reverse_path: ['Afro Samurai']                        
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
After the Rain                                              , subdir_files:   8, reverse_path: ['After the Rain']                      
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Ai Tenchi Muyo!                                             , subdir_files:  60, reverse_path: ['Ai Tenchi Muyo!']                     
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Air Gear                                                    , subdir_files:  25, reverse_path: ['Air Gear']                            
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Ajin                                                        , subdir_files:  26, reverse_path: ['Ajin']                                
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Akashic Records of Bastard Magic Instructor                 , subdir_files:  12, reverse_path: ['Akashic Records of Bastard Magic Instructor']
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Alderamin on the Sky                                        , subdir_files:  13, reverse_path: ['Alderamin on the Sky']                
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Aldnoah Zero                                                , subdir_files:  24, reverse_path: ['Aldnoah Zero']                        
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Alice & Zouroku                                             , subdir_files:  12, reverse_path: ['Alice & Zouroku']                     
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
All Out!!                                                   , subdir_files:  25, reverse_path: ['All Out!!']                           
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Amagi Brilliant Park                                        , subdir_files:  13, reverse_path: ['Amagi Brilliant Park']                
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
And you thought there is never a girl online                , subdir_files:  12, reverse_path: ['And you thought there is never a girl online']
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Angel Beats!                                                , subdir_files:  16, reverse_path: ['Angel Beats!']                        
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
anohana The Flower We Saw That Day                          , subdir_files:  11, reverse_path: ['anohana The Flower We Saw That Day']  
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Another                                                     , subdir_files:  12, reverse_path: ['Another']                             
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Arata The Legend                                            , subdir_files:  12, reverse_path: ['Arata The Legend']                    
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Arc The Lad                                                 , subdir_files:  26, reverse_path: ['Arc The Lad']                         
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Area 88 (2004)                                              , subdir_files:  12, reverse_path: ['Area 88 (2004)']                      
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Argento Soma                                                , subdir_files:  26, reverse_path: ['Argento Soma']                        
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Aria - The Natural                                          , subdir_files:  26, reverse_path: ['Aria - The Natural']                  
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Aria the Scarlet Ammo                                       , subdir_files:  12, reverse_path: ['Aria the Scarlet Ammo']               
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Armed Librarians Book of Bantorra                           , subdir_files:  27, reverse_path: ['Armed Librarians Book of Bantorra']   
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Assassination Classroom                                     , subdir_files:  47, reverse_path: ['Assassination Classroom']             
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Astro Fighter Sunred                                        , subdir_files:  52, reverse_path: ['Astro Fighter Sunred']                
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Asura Cryin                                                 , subdir_files:  26, reverse_path: ['Asura Cryin']                         
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Attack on Titan                                             , subdir_files:  42, reverse_path: ['Attack on Titan']                     
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Avatar The Last Airbender                                   , subdir_files:  60, reverse_path: ['Avatar The Last Airbender']           
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
B The Beginning                                             , subdir_files:  12, reverse_path: ['B The Beginning']                     
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Baby Steps                                                  , subdir_files:  50, reverse_path: ['Baby Steps']                          
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Baccano!                                                    , subdir_files:  16, reverse_path: ['Baccano!']                            
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series
Baki the Grappler                                           , subdir_files:  49, reverse_path: ['Baki the Grappler']                   
CACHE_PATH is not a valid folder: C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series

```

**Comment by sven-7** [comment]
I added the logs back, but it's still slow.

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/Beta/Scanners/Series/Absolute%20Series%20Scanner.py

Please try this version and report any ongoing issue.

**Comment by ZeroQI** [comment]
Don't seem to have the problem...
just uploaded new version.
Please let me know any issue. still scan in less than 2s per series including bleach

**Comment by sven-7** [comment]
Will do. The one earlier was still seeing issues where the item gets scanned in, then disappearing.  It seems like items that get scanned in on partial scans disappear at some point.  I have to manually scan or wait until the next scheduled for it to come back.

Will test the latest.

**Comment by sven-7** [comment]
Still having items removed on their first scan after being added.

See Plex removing it here:  

```
Mar 12, 2018 12:48:04.644 [7548] DEBUG - Path matched, we're reusing media item 252564
Mar 12, 2018 12:48:04.649 [7548] DEBUG - Removing 0 media items that were left.
Mar 12, 2018 12:48:04.649 [7548] DEBUG - Removing 1 directories that were left.
Mar 12, 2018 12:48:04.649 [7548] DEBUG - Deleting media item 269185.
Mar 12, 2018 12:48:04.650 [7548] DEBUG - Was connected to metadata item 284444, count is now 0.
Mar 12, 2018 12:48:04.650 [7548] DEBUG - Destroying metadata item 284444 (Cause and Effect)
Mar 12, 2018 12:48:04.651 [7548] DEBUG - Updating deletion state for metadata item 275879, is has a dead item count of 0.
Mar 12, 2018 12:48:04.651 [7548] DEBUG - Updating deletion state for metadata item 275878, is has a dead item count of 0.
Mar 12, 2018 12:48:04.652 [9608] DEBUG - HTTP requesting GET http://127.0.0.1:32400/:/metadata/flushMetadataCounterCache
Mar 12, 2018 12:48:04.652 [7548] DEBUG - Deleting directory [GARO -VANISHING LINE-] (6757)
Mar 12, 2018 12:48:04.653 [9608] DEBUG - HTTP 200 response from GET http://127.0.0.1:32400/:/metadata/flushMetadataCounterCache
Mar 12, 2018 12:48:04.675 [9608] DEBUG - HTTP requesting GET http://127.0.0.1:32400/:/metadata/notify/destroy?librarySectionID=2&ids=284444&types=4&parentIDs=275879&rootIDs=275878
Mar 12, 2018 12:48:04.676 [7548] DEBUG - Refreshing section 2 of type: 2
Mar 12, 2018 12:48:04.676 [9608] DEBUG - HTTP 200 response from GET http://127.0.0.1:32400/:/metadata/notify/destroy?librarySectionID=2&ids=284444&types=4&parentIDs=275879&rootIDs=275878
```

I've added the logs in and labeled them pre and post.

[Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1803730/Logs.zip)

**Comment by ZeroQI** [comment]
could you create a separate test library maybe pointing to the same folder ?
I do not have these changing behavior at all...

**Comment by sven-7** [comment]
It is the same with a test library.

Added 20 episodes of Garo.  Added the 21st. Then the 21st dropped off.  After another scan it came back.

**Comment by ZeroQI** [comment]
@sven-7 thanks a lot for all the tests. Super weird result though... i could scan all while on root folder scan but nothing is cached and will take a long time for every scan, i am unsure what to do... What is the best version of the scanner speed and stability wise? the current version supports plexignore and can be adapted easily... I believe i need to choose between grouping folders and fast/cacheable scanner calls...

**Comment by EndOfLine369** [comment]
@ZeroQI or both and go back to how I originally added in grouping folder support. Where it defaults to standard Plex driven fast/cacheable scanner calls unless a trigger (string or file) is found for it to run as a grouping folder root full scan.

**Comment by sven-7** [comment]
I think this was the version the add/delete/add started in:  db068a6 or ff0e71c. The speed was fixed in db068a6 and subsequent improvements.

**Comment by ZeroQI** [comment]
@sven-7 Thanks for the tests, i trust you but it is difficult to resolve something i don't see...
 i spotted a difference between that and the version prior and call to scan was modified now though:
- files[] is filename only
- path is relatibe
- dirs is list of fullpath dir
I hope it solves the issue, the files were added fullpath, could have messed things up a bit...

**Comment by sven-7** [comment]
So...new problem, maybe this will help solve it?

Plex seems to initate a scan, but nothing happens.  I see it in the logs for Plex, but ASS doens't do anything nor generate any logs.  If I manually scan, it will then add.

```
Mar 15, 2018 19:05:14.989 [4344] INFO - Plex Media Scanner v1.12.1.4871-6daee94e2 - Microsoft PC x64 - build: windows-i386 - GMT -04:00
Mar 15, 2018 19:05:14.990 [4344] INFO - Windows version: 6.2 (Build 9200), language en-US
Mar 15, 2018 19:05:14.990 [4344] INFO - 8 4200 MHz processor(s): Architecture=0, Level=6, Revision=40457 Processor Identifier=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
Mar 15, 2018 19:05:14.993 [4344] DEBUG - "C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Scanner.exe" --scan --refresh --section 2 --directory "F:\Series\Laid-Back Camp" 
Mar 15, 2018 19:05:15.164 [12404] DEBUG - Opening 20 database sessions to library (com.plexapp.plugins.library), SQLite 3.13.0, threadsafe=1
Mar 15, 2018 19:05:15.242 [12404] DEBUG - Scanning Anime Series using en(Absolute Series Scanner) with 0 current media items and 1 section locations in the database...
Mar 15, 2018 19:05:15.242 [11640] DEBUG - HTTP requesting GET http://127.0.0.1:32400/:/metadata/notify/cullTimeline?librarySectionID=2&sinceTime=1521153915
Mar 15, 2018 19:05:15.244 [11640] DEBUG - HTTP 200 response from GET http://127.0.0.1:32400/:/metadata/notify/cullTimeline?librarySectionID=2&sinceTime=1521153915
Mar 15, 2018 19:05:15.978 [12404] DEBUG - Performing a scan with 'Absolute Series Scanner' (language: en virtual: 0).
Mar 15, 2018 19:05:15.978 [12404] DEBUG -   * Scanning F:\Series\Laid-Back Camp
Mar 15, 2018 19:05:15.982 [12404] DEBUG -     * Scanning directory F:\Series\Laid-Back Camp (parent: yes)
Mar 15, 2018 19:05:15.983 [12404] DEBUG - Adding file for scanner: "F:\Series\Laid-Back Camp\Laid-Back Camp - 1 - Mount Fuji and Curry Noodles.mkv"
Mar 15, 2018 19:05:15.983 [12404] DEBUG - Adding file for scanner: "F:\Series\Laid-Back Camp\Laid-Back Camp - 10 - Clumsy Travellers and Camp Meetings.mkv"
Mar 15, 2018 19:05:15.983 [12404] DEBUG - Adding file for scanner: "F:\Series\Laid-Back Camp\Laid-Back Camp - 11 - Christmas Camp!.mkv"
Mar 15, 2018 19:05:15.983 [12404] DEBUG - Adding file for scanner: "F:\Series\Laid-Back Camp\Laid-Back Camp - 2 - Welcome to the Outdoor Activities Club!.mkv"
Mar 15, 2018 19:05:15.983 [12404] DEBUG - Adding file for scanner: "F:\Series\Laid-Back Camp\Laid-Back Camp - 3 - Mount Fuji and Relaxed Hot Pot Camp.mkv"
Mar 15, 2018 19:05:15.983 [12404] DEBUG - Adding file for scanner: "F:\Series\Laid-Back Camp\Laid-Back Camp - 4 - The Outdoor Activities Club and the Solo Camping Girl.mkv"
Mar 15, 2018 19:05:15.983 [12404] DEBUG - Adding file for scanner: "F:\Series\Laid-Back Camp\Laid-Back Camp - 5 - Two Camps, Two Campers' Views.mkv"
Mar 15, 2018 19:05:15.983 [12404] DEBUG - Adding file for scanner: "F:\Series\Laid-Back Camp\Laid-Back Camp - 6 - Meat and Fall Colors and the Mystery Lake.mkv"
Mar 15, 2018 19:05:15.983 [12404] DEBUG - Adding file for scanner: "F:\Series\Laid-Back Camp\Laid-Back Camp - 7 - A Night on the Lake Shore and Campers.mkv"
Mar 15, 2018 19:05:15.983 [12404] DEBUG - Adding file for scanner: "F:\Series\Laid-Back Camp\Laid-Back Camp - 8 - Exams, Caribou, Steamed Buns, Yum!.mkv"
Mar 15, 2018 19:05:15.983 [12404] DEBUG - Adding file for scanner: "F:\Series\Laid-Back Camp\Laid-Back Camp - 9 - A Night of Navigator Nadeshiko and Hot Spring Steam.mkv"
Mar 15, 2018 19:05:15.985 [12404] DEBUG - Directory had 11 files, database had 0 files, can't skip.
Mar 15, 2018 19:05:15.988 [12404] DEBUG - Removing 0 media items that were left.
Mar 15, 2018 19:05:15.988 [12404] DEBUG - Removing 0 directories that were left.
Mar 15, 2018 19:05:15.988 [12404] DEBUG - Updating directory 'Laid-Back Camp' (ID 6774) to time 2018-03-15 19:04:14.
Mar 15, 2018 19:05:16.017 [12404] DEBUG - Refreshing section 2 of type: 2
Mar 15, 2018 19:05:16.280 [6132] DEBUG - Refreshing 0 IDs.
```

**Comment by ZeroQI** [comment]
Installed Plex Media Server for windows
i had an issue with scudlee movie collection, but resolved itself, but no issue on 2 separate test libraries...
I don't want to mess up your plex database and stuff, but i cannot reproduce the issue and i need to know if i need to re-code the scanner or not...
in the meantime trying to code tvdb api v2 which uses json, might be able to load multiple language titles from thetvdb and trying to find a better systems for collections. Would love to use grouping folders as collections, BUT i need the scanner on point without using tags to flag grouping folders, so might need to further rely on your ongoing tests... Wrote a bit from traileradicts but no reply for an api key...

**Comment by ZeroQI** [comment]
@sven-7 Thanks to you, i realised i had removed from dirs all folders and that's why normal plex calls weren't made anymore to series folders and their subfolders... Now the normal scanner call the folders and only for grouping folders do i call manually the series folder inside grouping folders and prevent normal . only folders with actionable files are called so it is pretty optimised and take 4s instead of 25s now...

**Comment by sven-7** [comment]
It's working!! 

I'm not seeing any lingering issues.  Nothing is disappearing or not scanning anymore.  I'm not seeing any errors.  Speed seems to be good as well.   Glad you were able to spot it.  Sorry for my poor descriptions on the issue.

I think this is the one.

**Comment by ZeroQI** [comment]
Thank you, you honestly helped, have been at it since 5am... 
This one was a pain to write for, since:
- there is no documentation on scanner behaviour
- errors rarely give the line just stay the scanner had an error which is annoying as hell
- i want grouping folders with plex caching which i didn't though possible... until now :D

So in short, great news and thanks again!

FYI, i just released now a HAMA version which will create agent logs in agent data folders with the same name as the scanner, in a folder with the library name IF you the agent can access library XML (on my Synology NAS but not on Windows) unless you create the .../Plex Media Server/X-Plex-Token.id file with the token inside.

Have a look at the logs in Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs, they look really good, names are like:
- Darling in the FranXX.filelist.log
- Darling in the FranXX.scanner.log
- Darling in the FranXX.agent-search.log
- Darling in the FranXX.agent-update.log

That should help troubleshooting greatly and also list the filename in plex usual agent log
I can now add grouping folders as collection, probably with a "Local" Metadata source

Do you have a wish list for collection field, like how it should behave ?
Please let me know any issues

**Comment by sven-7** [comment]
The current version of the scanner and the new HAMA are working really well.  I like the new logging. 

I can't think of anything specific for the collections. I did some custom collections when Plex updated how they did it a few weeks ago, but nothing much since.  I'll look into it some.

**Comment by ZeroQI** [comment]
@sven-7 Thanks for this message, i am very happy to ear that

I noticed searches even when restarting the agent were very fast so much better.
If no more issues are present might integrate the code as master branch

I did some further coding, and the Prefs verification function now check quite more for errors and indicate changes towards the default settings

Here is the development axis for now
- Grouping folders to go directly in a collection now that you can tell libraries to hide series in a collection, and with the hiding if a single season only, the movies in series libraries look so much better. This will be through a Local.py source.
- TVDB v2 api in progress, will support multiple languages for episodes so the language selection works as it should. right now, only works if selecting anidb as source first. The language of text will be as always the language of the library.
- Pending api key from TrailerAddicts
- Planning maybe a NFO file loader in Local.py source if people wanted a local database

**Comment by ZeroQI** [comment]
Pushed Hama code, created a collection if using grouping folders like 'Dragon Ball Series/Dragon Ball Super
When creating/editing the library:
- Collections: 'Hide items which are in collections'
- Seasons: 'Hide for single-seasons series'
This way you see collections with series inside and no season folders if movies or single season series

**Comment by sven-7** [comment]
Nice, that's good to know. I'll grab the latest for both today and check it out.

**Comment by ZeroQI** [comment]
Have re-written AnimeLists, will gather more info that before, and to prepare for true bidirectionnal mapping lists. will allow with thetvdbguids to download the relevant anidb xml and map all like it should, but that's tricky since the xml was built to have one anidb serie mapped to tvdb, the other way around is a nightmare

**Comment by sven-7** [comment]
That will be pretty interesting. If I'm not mistaken, before for a show like Sword Art Online, it would map the TVDBID to AniDB (a8692) which is season 1, but not season 2 which is AniDB (a10376), right?

**Comment by ZeroQI** [comment]
Correct. If using multiple season it map back tvdb to anidb but 1 season. Tried to hack to make it multiple seasons without specials but failed...
Also coding after tvdbv2 api and will download titles in multiple languages so the agent behave like it should...
However it will only download the anidb XML needed...
Hopefully people speaking other languages will appreciate true language order working as designed

**Comment by ZeroQI** [comment]
@sven-7 latest update was meant to solve that. it now loads multiple anidb xmls for tvdb numbered (tvdbid or season>=2). if doesn't work please give me the file and folder names so i can reproduce
